DROP TABLE INDEBT_SALARY
CREATE TABLE INDEBT_SALARY (
	DEPT_AGENCY_NAME VARCHAR PRIMARY KEY,
	ANNUAL_SALARY FLOAT
	TOTAL_EMPLOYEES INT NOT NULL
	EMPLOYEES_WITH_DEBT INT NOT NULL
	PERCENT_EMPLOYEES_WITH_DEBT FLOAT(5) NOT NULL
	TOTAL_AMOUNT_DUE FLOAT NOT NULL
);

SELECT * FROM INDEBT_SALARY